<html>
<head>
    <title>AjaxChat</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js">
    </script>
    <script>

        var lpOnComplete = function(response) {
            if(response.length > 0){
                $('#msgArea').html(response);
                $('#msgArea')[0].scrollTop = $('#msgArea')[0].scrollHeight;
            }
            lpStart();
        };

        var lpStart = function() {

            setInterval(function(){
                $('#msgArea').load('<?php echo $this->_config['data-file']['channel_path'].DIRECTORY_SEPARATOR.$channel; ?>?' + Math.random() , null , function() { $('#msgArea')[0].scrollTop = $('#msgArea')[0].scrollHeight; } );
            },3000);

            //$.post('/getmsg.php', {}, lpOnComplete);
        };

        $(document).ready(function(){
            //  setInterval(function(){
            //$('#msgArea').load('db.txt?'+Math.random());
            //$('#msgArea')[0].scrollTop = $('#msgArea')[0].scrollHeight;
            //},2000);

            $('#msgform').submit( function() {
                $.ajax('index.php',
                    {
                        type:'POST',
                        data: {
                            msg: $('#msgform input[name="msg"]').attr('value'),
                            channel: '<?php echo $channel; ?>'
                        },
                        complete: function() {
                            //$('#msgArea').load('db.txt?'+Math.random());
                            $('#msgform input[name="msg"]').attr('disabled', 'true');
                            $('#msgform input[type="submit"]').attr('disabled','true');
                            $('#msgform input[name="msg"]').attr('value', 'please wait...');
                            setTimeout( function(){
                                $('#msgform input[name="msg"]').removeAttr('disabled');
                                $('#msgform input[type="submit"]').removeAttr('disabled');
                                $('#msgform input[name="msg"]').attr('value', '');
                            },5000);
                        }
                    }
                );

                $('#msgform input[name="msg"]').attr('value','');
                return false;
            });

            $('#msgArea')[0].scrollTop = $('#msgArea')[0].scrollHeight;

            lpStart();
        });

    </script>
    <link id="style_link" rel="stylesheet" type="text/css" href="css/style.css">
</head>
<body>

<div id="msgArea" style="clear:both;width:100%;height:400px;border:2px solid grey;overflow-y:scroll;overflow-x:hidden;"><?php readfile($this->_config['data-file']['channel_path'].DIRECTORY_SEPARATOR.$channel); ?></div>
<form method="POST" id="msgform">
    <input type="text" name="msg" style="width:100%;" autocomplete="off">
    <input type="hidden" name="channel" value="<?php echo $channel; ?>">
    <input type="submit" value="Send">
</form>
</body>